spring:
  application:
    name: litechess-monolith
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/vue-test
server:
  port: 8080
# logging:
#   level:
#     org.springframework.messaging: DEBUG
#     org.springframework.security: DEBUG